# Workflow
# should have name:
name: Hello

#on tell when wf runs
on:
  workflow_dispatch:
# Jobs
# should be in workflow
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to everyone
        run: echo "Hello Dosto"
# steps
# should be in jobs
# actions
# should be in workflow
